### ISSUE TITLE
Feature - Dictionnary

### ISSUE THREAD

**Issue by raefko** [FuzzingLabs/cairo-fuzzer#37]
- Add usage of dictionnary for fuzzing

**Comment by raefko** [comment]
Cairo-fuzzer already have
```
    #[arg(
        long,
        help = "Path to the inputs folder to load",
        name = "INPUTFOLDER",
        default_value = ""
    )]
    pub inputfolder: String,

    #[arg(
        long,
        help = "Path to the crashes folder to load",
        name = "CRASHFOLDER",
        default_value = ""
    )]
    pub crashfolder: String,
    ```
That loads all the inputs into the mutator database. Is it what you wanted?

**Comment by pventuzelo** [comment]
No it's more a dictionary like libfuzzer or honggfuzz like -dict where user can provide they own interesesting value.

Example: evm opcode for kakarot

**Comment by raefko** [comment]
Feature added, you can try it using --dict
